version: 2.1

orbs:
  sonarcloud: sonarsource/sonarcloud@1.0.1
  snyk: snyk/snyk@0.0.8
  codecov: codecov/codecov@1.0.2

# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
#
#   E X E C U T O R S:
#   ------------------------------------------------------------------------
#   Executors to run a job with
#
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #

executors:
  # Base image for publishing
  docker-publisher:
    docker:
      - image: circleci/buildpack-deps:stretch
  # Base image for building node based environments
  node-builder:
    docker:
      - image: circleci/node:12

# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
#
#   P A T T E R N S:
#   ------------------------------------------------------------------------
#   Patterns are used to provide reuseable samples of code.
#   This is a yml feature to reduce redundancy.
#
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #

defaults: &defaults
  working_directory: ~/barista
  docker:
    - image: circleci/node:12


npm_cache: &npm_cache
  keys:
    - npm-packages-{{ checksum "package-lock.json" }}
    - npm-packages-


# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
#
#   J O B S:
#   ------------------------------------------------------------------------
#   Jobs that can be executed
#
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #

jobs:

# - install npm dependencies
  install:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          <<: *npm_cache
      - run:
          name: Install npm dependencies 🐍
          command: npm ci
      - save_cache:
          key: npm-packages-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - persist_to_workspace:
          root: ~/barista
          paths:
            - .

# - sonar checks
  sonar:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/barista
      - sonarcloud/scan

# - snyk security checks
  security-checks:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/barista
      - snyk/scan:
          organization: dynatrace-oss

# - check formatting if all files are formatted with prettier
  check-formatting:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/barista
      - run: yarn format:check --base=origin/master

# - static codeanalysis of the files
  lint:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/barista
      - run: ./node_modules/.bin/nx workspace-lint
      - run: yarn affected:lint --base=origin/master --parallel

# - static codeanalysis of the style files
  lint-styles:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/barista
      - run: yarn affected --target=lint-styles --base=origin/master --parallel

# - build all the packages
  build:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/barista
      - run: yarn affected:build --base=origin/master --parallel --configuration=production
      - save_cache:
          key: build-{{ .Environment.CIRCLE_WORKFLOW_ID }}
          paths:
            - dist
      - store_artifacts:
          path: dist

# - run unit tests
  unit-test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/barista
      - run: yarn affected:test --base=origin/master --parallel --runInBand
      - codecov/upload:
          file: coverage/**/*.json
          upload_name: Unit test coverage
      - store_test_results:
          path: dist/test-results
      - store_artifacts:
          path: dist/test-results


# - run end to end tests
  e2e-test:
    environment:
      BROWSERSTACK_USE_AUTOMATE: 1
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/barista
      - run: yarn affected:e2e --base=origin/master --configuration=remote-pr
      - store_test_results:
          path: dist/components-e2e
      - store_artifacts:
          path: dist/components-e2e
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
#
#   W O R K F L O W S:
#   ------------------------------------------------------------------------
#   Jobs are getting executed through workflows,
#   they are creating the pipeline.
#
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #

workflows:
  version: 2.1
# - Runs on every PR check
  pr_check:
    jobs:
      - install
      - check-formatting:
          requires:
            - install
      - sonar:
          requires:
            - install
      - security-checks:
          requires:
            - install
      - lint:
          requires:
            - install
      - lint-styles:
          requires:
            - install
      - unit-test:
          requires:
            - install
      - e2e-test:
          requires:
            - install
      # - build:
      #     requires:
      #       - install
